export enum ERROR_CODES {
  // User
  USER_NOT_FOUND = 1000,

  // Portfolio
  PORTFOLIO_NOT_FOUND = 2000,
  PORTFOLIO_WITH_NAME_EXISTS = 2001,

  // Share
  SHARE_NOT_FOUND = 3000,
  SHARE_WITH_SYMBOL_EXISTS = 3001,

  // Trade
  TRADE_NOT_FOUND = 4000,
  PORTFOLIO_SHARE_NOT_FOUND = 4001,
  INSUFFICIENT_AMOUNT_OF_SHARES = 4002,
}
